<#
.SYNOPSIS
    Back up ESXi host configurations with interactive menu, dry-run, log rotation, and HTML summary.
.DESCRIPTION
    Connects to vCenter, standalone hosts, or a CSV list and runs Get-VMHostFirmware to back up each host's
    configuration bundle to a timestamped per-host folder. Supports dry-run mode, auto log rotation
    (removes HTML summaries older than 14 days), color-coded console output, and an HTML summary report
    with per-host status (SUCCESS, FAILURE, DRY-RUN).
.NOTES
    Author  : Abi Perez and Allen Johnson
    Date    : 2025-07-28
    Version : 2.0
    Module  : VMware.PowerCLI
    Repo    : vmware-esxi-powershell
    Changes : Interactive menu, dry-run, CSV import, HTML summary, auto log rotation

    ESXi Host Configuration Backup Script
    Version: 2.0
    Author: Abi Perez and Allen Johnson
    Last Updated: 2025-07-28

    Updates:
    - Added interactive menu (vCenter, Standalone, CSV)
    - Added dry-run mode with emojis
    - Added color-coded console output
    - Integrated CSV import option
    - HTML summary generation with status colors
    - Auto log rotation
    - Browser prompt for summary
#>

Clear-Host

# === Configuration ===
$DefaultOutputDir = "C:\esxihost_backups"
$LogRetentionDays = 14
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"

# === Helper Functions ===
function Remove-OldLogs {
    param ($path, $days, [ref]$summary)
    $cutoff = (Get-Date).AddDays(-$days)
    Get-ChildItem -Path $path -Filter "backup_summary_*.html" -ErrorAction SilentlyContinue |
    Where-Object { $_.LastWriteTime -lt $cutoff } |
    ForEach-Object {
        try {
            Remove-Item -Path $_.FullName -Force
            $summary.Value += "🗑 LOG ROTATION: Deleted old file $($_.Name)"
        }
        catch {
            $summary.Value += "⚠️ LOG ROTATION ERROR: Could not delete $($_.Name): $_"
        }
    }
}

function Format-HostSummary {
    param ($hostname, $version, $build, $status, $duration)
    return "$hostname | $version | $build : $status ($duration sec)"
}

function Show-Summary {
    param ($summaryArray, $isDryRun)
    $header = if ($isDryRun) { "🧪 DRY-RUN Summary" } else { "📄 Backup Summary" }
    Write-Host "`n===== $header =====" -ForegroundColor Gray
    foreach ($line in $summaryArray) {
        $hostName, $result = $line -split " : ", 2
        $color = if ($result -like "SUCCESS*") { "Green" }
        elseif ($result -like "FAILURE*") { "Red" }
        elseif ($result -like "DRY-RUN*") { "Yellow" }
        elseif ($result -like "🗑*") { "DarkGray" }
        else { "Gray" }
        Write-Host "$hostName => $result" -ForegroundColor $color
    }
    $count = ($summaryArray | Where-Object { $_ -match " : " }).Count
    Write-Host "`nTotal hosts processed: $count`n" -ForegroundColor White
}

function Export-SummaryToHtml {
    param ($summaryArray, $path, $timestamp, $username)
    $htmlPath = Join-Path $path "backup_summary_$timestamp.html"

    $html = @()
    $html += "<html><head><meta charset='UTF-8'><style>"
    $html += "body { font-family: Consolas, monospace; background-color: #121212; color: #eee; padding: 1rem; }"
    $html += "table { border-collapse: collapse; width: 100%; margin-top: 1rem; }"
    $html += "th, td { border: 1px solid #555; padding: 6px; text-align: left; }"
    $html += "th { background-color: #1e1e1e; color: #fff; }"
    $html += ".success { color: lightgreen; }"
    $html += ".failure { color: salmon; }"
    $html += ".dryrun { color: khaki; }"
    $html += ".log { color: gray; }"
    $html += "</style></head><body>"
    $html += "<h2>ESXi Host Backup Summary - $timestamp</h2>"
    $html += "<p><strong>Generated by:</strong> $username</p>"
    $html += "<table><tr><th>Host</th><th>ESXi Version</th><th>Build</th><th>Status</th><th>Duration</th></tr>"

    foreach ($line in $summaryArray) {
        if ($line -match "^(?<host>.*?) \| (?<version>.*?) \| (?<build>.*?) : (?<status>.*?) \((?<duration>.*?) sec") {
            $vmHostName = $matches['host']
            $version = $matches['version']
            $build = $matches['build']
            $statusText = $matches['status']
            $duration = $matches['duration'] + " sec"
        }
        elseif ($line -match "^(?<host>.*?) \| (?<version>.*?) \| (?<build>.*?) : (?<status>.*)$") {
            $vmHostName = $matches['host']
            $version = $matches['version']
            $build = $matches['build']
            $statusText = $matches['status']
            $duration = ""
        }
        else {
            continue
        }

        $class = if ($statusText -like "SUCCESS*") { "success" }
        elseif ($statusText -like "FAILURE*") { "failure" }
        elseif ($statusText -like "DRY-RUN*") { "dryrun" }
        else { "log" }

        $html += "<tr><td>$vmHostName</td><td>$version</td><td>$build</td><td class='$class'>$statusText</td><td>$duration</td></tr>"
    }

    $html += "</table></body></html>"
    $html | Out-File -FilePath $htmlPath -Encoding UTF8
    Write-Host "📄 HTML summary exported to $htmlPath" -ForegroundColor Yellow
    return $htmlPath
}

# === Interactive Menu ===
Write-Host "==========================================" -ForegroundColor Yellow
Write-Host "ESXi Host Configuration Backup Script" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Yellow
Write-Host "Select connection method:" -ForegroundColor White
Write-Host "[1] vCenter (cluster-based or all hosts)"
Write-Host "[2] Standalone ESXi host(s)"
Write-Host "[3] Import from hosts.csv"
$connectionMode = Read-Host "Enter selection [1/2/3]"

# === Dry-run Option ===
$dryRunInput = Read-Host "Enable dry-run mode? (Y/N) [N]"
$dryRun = ($dryRunInput -and $dryRunInput.Trim().ToUpper() -eq "Y")
if ($dryRun) {
    Write-Host "🧪 DRY-RUN MODE ENABLED" -ForegroundColor Yellow
}

# === Output Directory ===
$baseOutputDir = Read-Host "Enter backup directory [$DefaultOutputDir]"
if ([string]::IsNullOrWhiteSpace($baseOutputDir)) { $baseOutputDir = $DefaultOutputDir }
New-Item -ItemType Directory -Path $baseOutputDir -Force | Out-Null

$summary = @()
if (-not $dryRun) {
    Remove-OldLogs -path $baseOutputDir -days $LogRetentionDays -summary ([ref]$summary)
}

# === Get Hosts ===
$VMhosts = @()
$viCredential = Get-Credential

switch ($connectionMode) {
    "1" {  # vCenter
        $vcenter = Read-Host "Enter vCenter Server name or IP"
        try {
            Connect-VIServer -Server $vcenter -Credential $viCredential -ErrorAction Stop
        } catch {
            Write-Host "❌ ERROR: Could not connect to vCenter $vcenter" -ForegroundColor Red
            exit
        }
        $clusterName = Read-Host "Enter cluster name (leave blank for all hosts)"
        if ([string]::IsNullOrWhiteSpace($clusterName)) {
            $VMhosts = Get-VMHost
        } else {
            $VMhosts = Get-Cluster -Name $clusterName | Get-VMHost
        }
    }
    "2" {  # Standalone
        $serverInput = Read-Host "Enter standalone ESXi hostnames/IPs (comma-separated)"
        foreach ($esxiHost in ($serverInput -split "," | ForEach-Object { $_.Trim() })) {
            try {
                $viSession = Connect-VIServer -Server $esxiHost -Credential $viCredential -ErrorAction Stop
                $VMhosts += Get-VMHost -Server $viSession
            } catch {
                Write-Host "❌ ERROR: Could not connect to $esxiHost" -ForegroundColor Red
            }
        }
    }
    "3" {  # CSV
        $csvPath = Read-Host "Enter path to hosts.csv"
        if (-not (Test-Path $csvPath)) {
            Write-Host "❌ CSV file not found at $csvPath" -ForegroundColor Red
            exit
        }
        $csvHosts = Import-Csv $csvPath
        foreach ($row in $csvHosts) {
            try {
                $viSession = Connect-VIServer -Server $row.Host -User $row.User -Password $row.Password -ErrorAction Stop
                $VMhosts += Get-VMHost -Server $viSession
            } catch {
                Write-Host "❌ ERROR: Could not connect to $($row.Host)" -ForegroundColor Red
            }
        }
    }
    default {
        Write-Host "❌ Invalid selection" -ForegroundColor Red
        exit
    }
}

# === Backup Loop ===
foreach ($vmhost in $VMhosts) {
    $hostname = $vmhost.Name
    $version = $vmhost.Version
    $build = $vmhost.Build
    $hostOutputDir = Join-Path $baseOutputDir "$hostname-$timestamp"
    New-Item -ItemType Directory -Path $hostOutputDir -Force | Out-Null

    if ($dryRun) {
        $summary += Format-HostSummary $hostname $version $build "DRY-RUN ✅" 0
    } else {
        $startTime = Get-Date
        try {
            Get-VMHostFirmware -VMHost $vmhost -BackupConfiguration -DestinationPath $hostOutputDir | Out-Null
            $duration = [math]::Round((New-TimeSpan -Start $startTime).TotalSeconds, 1)
            Write-Host "✅ [$hostname] Backup completed in $duration sec." -ForegroundColor Green
            $summary += Format-HostSummary $hostname $version $build "SUCCESS ✅" $duration
        } catch {
            $duration = [math]::Round((New-TimeSpan -Start $startTime).TotalSeconds, 1)
            Write-Host "❌ [$hostname] Backup FAILED after $duration sec." -ForegroundColor Red
            $summary += Format-HostSummary $hostname $version $build "FAILURE ❌" $duration
        }
    }
}

# === Summary Output ===
Show-Summary -summaryArray $summary -isDryRun:$dryRun
$htmlFile = Export-SummaryToHtml -summaryArray $summary -path $baseOutputDir -timestamp $timestamp -username $viCredential.UserName

# === Open HTML Summary ===
$openHtml = Read-Host "Open HTML summary now? (Y/N) [Y]"
if (-not $openHtml -or $openHtml.Trim().ToUpper() -eq "Y") {
    Start-Process $htmlFile
}

Disconnect-VIServer * -Confirm:$false
Write-Host "🔌 Disconnected from all servers." -ForegroundColor Cyan
